davinci: fix compilation error when using mach/system.h
include/mach/system.h uses the cpu_do_idle() function which is
defined in asm/proc-fns.h. Without this patch including system.h
leads to error of the sort:

error: implicit declaration of function 'cpu_do_idle'

Signed-off-by: Sekhar Nori <nsekhar@ti.com>
Signed-off-by: Kevin Hilman <khilman@deeprootsystems.com>